version: "3.7"

services:
  app:
    image: devconf5296/wowtown_frontend:0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./key:/etc/nginx/key/
      - ./crt:/etc/nginx/crt/
    working_dir: /deploy
    restart: always