name: Refactor
description: 리팩터링할 기능 정의합니다.
labels: [refactor]
body:
  - type: textarea
    id: why-to-refactor
    attributes:
      label: 변경 사항
      description: 리팩터링을 하는 부분과 이유에 대해 설명합니다.
    validations:
      required: true